# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9c0288e4a76f2287b6af96acddccafc57c3a97ff2272e9112461e67db6881ad30f9b08223572ff04ce59627be6a14a3c04cf10d99e509f10dd78340a53ff508

test:
  secret_key_base: e38f6e78d332d4c5488628d68fc1e00e51340cc2a6ebee8782d4918b92e2ccd40189bcb469af0fd242bd375c569de6f50a557be200e1cc028e69e469df56a348

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
